session:
  key: PfJ4Hkf_glFG_S08LlxjmJMgHNhMSHY8LO7bxOP11bo=
superuser:
  login: elle
  password: 12345
database:
  host: db
  user: elle_dev
  password: dev_elle_pass
  database: dev_osu
redis:
  host: redis
credentials:
  client_id: $CLIENT_ID
  client_secret: $CLIENT_SECRET
  grant_type: "client_credentials"
  scope: "public"
  server_name: $SERVER_NAME
