session:
  key: PfJ4Hkf_glFG_S08LlxjmJMgHNhMSHY8LO7bxOP11bo=
superuser:
  login: elle
  password: 12345
database:
  host: "localhost:5050"
  user: elle_dev
  password: dev_elle_pass
  database: dev_osu
redis:
  host: "localhost:6379"