session:
  key: PfJ4Hkf_glFG_S08LlxjmJMgHNhMSHY8LO7bxOP11bo=
superuser:
  login: $SUPERUSER_NAME
  password: $SUPERUSER_PASSWORD
database:
  host: db
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD
  database: $POSTGRES_DB
redis:
  host: redis
credentials:
  client_id: $CLIENT_ID
  client_secret: $CLIENT_SECRET
  grant_type: "client_credentials"
  scope: "public"
  server_name: $SERVER_NAME
