version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osusettings
    ports:
      - 8080:8080
    environment:
      CLIENT_ID: 15033
      CLIENT_SECRET: dSbJw0V5RWbl3rBlOksmtNGHFPsz0PJDHlREOPPS
      SERVER_NAME: http://localhost:8080
    depends_on:
      - db
      - redis

  rank_updater:
    build:
      context: .
      dockerfile: Pollerfile
    container_name: rank_updater
    depends_on:
      - db
      - app
      - redis
    restart: always

#  nginx:
#    build:
#      context: .
#      dockerfile: Nginxfile
#    container_name: nginx_osu
#    ports:
#      - 80:80
#    volumes:
#      #- ./nginx-conf:/etc/nginx/conf.d
#      - ./logs/nginx:/var/log/nginx
##      - ./www:/var/www
#    depends_on:
#      - app

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_osu
      POSTGRES_USER: elle_dev
      POSTGRES_PASSWORD: dev_elle_pass
    ports:
      - 5050:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  pgdata:
