version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osusettings
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev_osu
      POSTGRES_USER: elle_dev
      POSTGRES_PASSWORD: dev_elle_pass
    ports:
      - 5050:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  pgdata: