version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "dev_osu"
      POSTGRES_USER: "elle_dev"
      POSTGRES_PASSWORD: "dev_elle_pass"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"