"""empty message

Revision ID: 573060de1870
Revises: f5480b150f8c
Create Date: 2022-05-21 11:59:52.749420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573060de1870'
down_revision = 'f5480b150f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_active')
    # ### end Alembic commands ###
