"""empty message

Revision ID: f5480b150f8c
Revises: 
Create Date: 2022-04-23 12:37:31.890746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5480b150f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('osu_id')
    )
    op.create_table('keyboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sensor', sa.String(), nullable=True),
    sa.Column('switch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mousepad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playstyle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('superuser',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tablet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('last_updated', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('performance', sa.Float(precision=10), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('is_mouse', sa.Boolean(), nullable=True),
    sa.Column('playstyle_id', sa.Integer(), nullable=True),
    sa.Column('mouse_edpi', sa.Integer(), nullable=True),
    sa.Column('tablet_area_width', sa.Integer(), nullable=True),
    sa.Column('tablet_area_height', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('os_sens', sa.Integer(), nullable=True),
    sa.Column('os_accel', sa.Boolean(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('res_width', sa.Integer(), nullable=True),
    sa.Column('res_height', sa.Integer(), nullable=True),
    sa.Column('polling_rate', sa.Integer(), nullable=True),
    sa.Column('play_area_width', sa.Integer(), nullable=True),
    sa.Column('play_area_height', sa.Integer(), nullable=True),
    sa.Column('refresh_rate', sa.Integer(), nullable=True),
    sa.Column('raw_input', sa.Boolean(), nullable=True),
    sa.Column('mouse_id', sa.Integer(), nullable=True),
    sa.Column('mousepad_id', sa.Integer(), nullable=True),
    sa.Column('tablet_id', sa.Integer(), nullable=True),
    sa.Column('keyboard_id', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['keyboard_id'], ['keyboard.id'], ),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.ForeignKeyConstraint(['mousepad_id'], ['mousepad.id'], ),
    sa.ForeignKeyConstraint(['playstyle_id'], ['playstyle.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.ForeignKeyConstraint(['tablet_id'], ['tablet.id'], ),
    sa.PrimaryKeyConstraint('osu_id')
    )
    op.create_table('previous_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.Column('is_mouse', sa.Boolean(), nullable=True),
    sa.Column('playstyle_id', sa.Integer(), nullable=True),
    sa.Column('mouse_edpi', sa.Integer(), nullable=True),
    sa.Column('tablet_area_width', sa.Integer(), nullable=True),
    sa.Column('tablet_area_height', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('os_sens', sa.Integer(), nullable=True),
    sa.Column('os_accel', sa.Boolean(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('res_width', sa.Integer(), nullable=True),
    sa.Column('res_height', sa.Integer(), nullable=True),
    sa.Column('polling_rate', sa.Integer(), nullable=True),
    sa.Column('play_area_width', sa.Integer(), nullable=True),
    sa.Column('play_area_height', sa.Integer(), nullable=True),
    sa.Column('refresh_rate', sa.Integer(), nullable=True),
    sa.Column('raw_input', sa.Boolean(), nullable=True),
    sa.Column('mouse_id', sa.Integer(), nullable=True),
    sa.Column('mousepad_id', sa.Integer(), nullable=True),
    sa.Column('tablet_id', sa.Integer(), nullable=True),
    sa.Column('keyboard_id', sa.Integer(), nullable=True),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['keyboard_id'], ['keyboard.id'], ),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.ForeignKeyConstraint(['mousepad_id'], ['mousepad.id'], ),
    sa.ForeignKeyConstraint(['osu_id'], ['players.osu_id'], ),
    sa.ForeignKeyConstraint(['playstyle_id'], ['playstyle.id'], ),
    sa.ForeignKeyConstraint(['switch_id'], ['switch.id'], ),
    sa.ForeignKeyConstraint(['tablet_id'], ['tablet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previous_settings')
    op.drop_table('players')
    op.drop_table('tablet')
    op.drop_table('switch')
    op.drop_table('superuser')
    op.drop_table('playstyle')
    op.drop_table('mousepad')
    op.drop_table('mouse')
    op.drop_table('keyboard')
    op.drop_table('admins')
    # ### end Alembic commands ###
